name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Download Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 31
        build-tools-version: '31.0.0'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Run unit tests
      run: ./gradlew test

    - name: Run lint
      run: ./gradlew lint

    - name: Build Release APK
      # إذا عندك signing_config
      run: ./gradlew assembleRelease

    - name: Upload Release APK
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk
